name: CI

on:
  push:
    branches: [ devops ]

    workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build
      run: docker-compose up -d
    - name: upload
      uses: ishworkh/docker_image_artifact_upload@v1
      with:
        image: "bcl_web:v${{ github.run_number }}"
    - name: download
      uses: ishworkh/docker_image_artifact_download@v1
      with:
        image: "bcl_web:v${{ github.run_number }}"