name: CI

on:
  push:
    branches: [ devops ]

    workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: set up qemu
      uses: docker/setup-qemu-action@v1

    - name: set up docker buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: login to docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/devops:v${{ github.run_number }}
        cache_from: ${{ secrets.DOCKER_HUB_USERNAME }}/devops:buildcache
        cache_to: ${{ secrets.DOCKER_HUB_USERNAME }}/devops:buildcache,mode=max

#        let's add some text to preteng we changed the project